rules:
  color-hex-case: lower
  color-hex-length: short
  color-named: never
  declaration-bang-space-after: never
  declaration-block-no-duplicate-properties:
    - true
    - ignore: consecutive-duplicates
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-single-line-max-declarations: 1
  declaration-block-trailing-semicolon: always
  font-family-name-quotes: always-where-recommended
  font-family-no-missing-generic-family-keyword: true
  font-weight-notation: numeric
  function-calc-no-unspaced-operator: true
  function-comma-space-after: always
  function-linear-gradient-no-nonstandard-direction: true
  function-parentheses-space-inside: never
  function-url-quotes: never
  function-whitespace-after: always
  indentation: 2
  length-zero-no-unit: true
  number-leading-zero: never
  number-max-precision: 4
  property-no-vendor-prefix: true
  rule-empty-line-before: always
  selector-max-class: 2
  selector-max-id: 2
  selector-no-vendor-prefix: true
  shorthand-property-no-redundant-values: true
  string-no-newline: true
  string-quotes: double
  value-no-vendor-prefix: true
