env:
  browser: true
  es6: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: 2018
rules:
  arrow-parens:
    - error
    - as-needed
  curly:
    - error
    - all
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
    - avoidEscape: true
  max-len:
    - error
    - code: 80
      tabWidth: 2
  no-plusplus:
    - warn
    - allowForLoopAfterthoughts: true
  semi:
    - error
    - always
